0      #incont
1      #initsnap
EX     #basisset CB, LH, or EX
12     #nmax
6      #lmax
200    #nsteps
100    #noutbod
10     #noutlog
0.1    #dtime
1.0    #G
0.05   #eps
6.0    #abasis
0      #zeroodd
0      #zeroeven
1      #fixacc
0      #ubodlog
0      #outpcoef
SPL    #softening_type PLM or SPL
2      #mm_order
0.5    #theta
8      #n_leaf_limit
200    #n_group_limit
5.0    #cnfw
30.0   #rmax
5.0    #mh
